repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
bases:
  - environments.yaml
---
templates:
  default:
    missingFileHandler: Error
    values:
      - values.yaml.gotmpl
releases:
  - name: myargocd
    namespace: argocd
    chart: argo/argo-cd
    version: "8.1.3"
    inherit:
      - template: default
