myargocd:
  repoServer:
    # Mount your age key as a secret
    volumes:
      - name: age-secret-keys
        secret:
          secretName: argocd-age-key
          defaultMode: 0444
      - name: helmfile-cmp-tmp
        emptyDir: {}
    extraContainers:
      - name: helmfile-plugin
        image: travisghansen/argo-cd-helmfile:latest
        command: [/var/run/argocd/argocd-cmp-server]
        env:
          - name: SOPS_AGE_KEY_FILE
            value: /sops/age/keys.txt
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /sops/age
            name: age-secret-keys
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: helmfile-cmp-tmp
    env:
      - name: HELM_PLUGINS
        value: /home/argocd/.local/share/helm/plugins
      - name: SOPS_AGE_KEY_FILE
        value: /home/argocd/.config/sops/age/key.txt
      - name: HELM_SECRETS_BACKEND
        value: sops
argocd-apps:
  templates:
    - |
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: monitoring-app
      spec:
        destination:
          namespace: monitoring
          server: https://kubernetes.default.svc
        source:
          path: .
          repoURL: https://github.com/alexandreLITHAUD/infra-monitoring
          targetRevision: main
          plugin:
            name: helmfile
        sources: []
        project: default
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
